### PR TITLE
Hover effect added in sidebar

### LINKED ISSUE #9: Hover Effect in Sidebar or Navbar

### PR DESCRIPTION
**Pull request by amitmishra11**
resolves #9

### CODE REVIEW

**Comment by minhaj-313** [comment]
@amitmishra11  can you send me Screen Shot

**Comment by amitmishra11** [comment]
image


image

**Comment by amitmishra11** [comment]
@minhaj-313  above are the screen shots.

**Comment by minhaj-313** [comment]
Follow me and Like this Repositor, Thank You So Much for Contributing, Have a Nice Day @amitmishra11

**Pull request merged**
