### PR TITLE
hactoberfest2022

### PR DESCRIPTION
**Pull request by raj-hero**
Added text animations #44 . Mention issues if found any. Also, do add hacktoberfest-accepted tag if no issues are found.

### CODE REVIEW

**Comment by raj-hero** [comment]
@minhaj-313 Why does my hacktoberfest progile still shows not-accepted ? Do reply when you are free.
Thanks
Screen Shot 2022-10-03 at 6 39 48 PM

**Comment by minhaj-313** [comment]
> @minhaj-313 Why does my hacktoberfest profile still shows not-accepted for issue #44 and PR #54 ? Do reply when you are free. Thanks Screen Shot 2022-10-03 at 6 39 48 PM

It takes time to update in my profile same problem here

**Comment by raj-hero** [comment]
> > @minhaj-313 Why does my hacktoberfest profile still shows not-accepted for issue #44 and PR #54 ? Do reply when you are free. Thanks Screen Shot 2022-10-03 at 6 39 48 PM
> 
> It takes time to update in my profile same problem here

Thanks for the reply.
If the issue doesn't resolve, do tell the steps to be done to get it resolved.
Thanks:)

**Comment by minhaj-313** [comment]
> > > @minhaj-313 Why does my hacktoberfest profile still shows not-accepted for issue #44 and PR #54 ? Do reply when you are free. Thanks Screen Shot 2022-10-03 at 6 39 48 PM
> > 
> > 
> > It takes time to update in my profile same problem here
> 
> Thanks for the reply. If the issue doesn't resolve, do tell the steps to be done to get it resolved. Thanks:)

I am also facing this issue 😅

**Comment by minhaj-313** [comment]
> > > > > @minhaj-313 Why does my hacktoberfest profile still shows not-accepted for issue #44 and PR #54 ? Do reply when you are free. Thanks Screen Shot 2022-10-03 at 6 39 48 PM
> > > > 
> > > > 
> > > > It takes time to update in my profile same problem here
> > > 
> > > 
> > > Thanks for the reply. If the issue doesn't resolve, do tell the steps to be done to get it resolved. Thanks:)
> > 
> > 
> > I am also facing this issue 😅
> 
> It's showing accepted Thanks:)

Your Welcome,
Great.

**Pull request merged**
