### PR TITLE
added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by AyushSarode**
please label it as hacktoberfest-accepted

### CODE REVIEW

**Comment by minhaj-313** [comment]
Attach My Repository Links 
Its not Proper Way

**Comment by AyushSarode** [comment]
sure

**Review by AyushSarode — COMMENTED** [review]
Updated CONTRIBUTING.md as per your requirement.
please label it as a hacktoberfest-accepted for hacktoberfest

**Comment by minhaj-313** [comment]
Please give star to this repository and Follow me,
Thank You.

**Pull request merged**
