### PR TITLE
updates links and bugs in social meadia handle

### PR DESCRIPTION
**Pull request by manipta**
Hey done with the editing...sorry for being this late... was looking for more bugs :)
image

### CODE REVIEW

**Comment by minhaj-313** [comment]
Thank You So Much For contributing.

**Review by manipta — COMMENTED** [review]
Please Review yourself once

**Comment by manipta** [comment]
thanks for merging

**Comment by minhaj-313** [comment]
Follow me and please give star to this Repository, Have a Nice Day

**Pull request merged**
